apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: javahometech
      image: likithreddysiddala/javahometech:v1
      ports:
        - containerPort: 8080
