apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: likithreddysiddala/nodeapp:92fe149
      ports:
        - containerPort: 8080
